from services.teacher_service import TeacherService
from services.student_service import StudentService
from services.class_service import ClassService
from services.subject_service import SubjectService
